### ISSUE TITLE
Miswritten file

### ISSUE THREAD

**Issue by ballsystemlord** [xypron/kernel-firefly-rk3399#2]
I'm not certain whose responsibility this is (yours, or Torvalds et. al.), but basically it seems as though the file linux/deploy/version lacks shell line continuation characters.
`
linux/deploy/version: 4: linux/deploy/version: 4.18.11-D001-arm64: not found
linux/deploy/version: 5: linux/deploy/version: make[2]:: not found
`
`
cat linux/deploy/version
#!/bin/sh
echo \
make[2]: Entering directory '/home/me/working/kernel-firefly-rk3399/linux'
4.18.11-D001-arm64
make[2]: Leaving directory '/home/me/working/kernel-firefly-rk3399/linux'
`

Here is my complete log:
[log2.txt.zip](https://github.com/xypron/kernel-firefly-rk3399/files/2729818/log2.txt.zip)

Thanks!

**Comment by xypron** [comment]
@ballsystemlord 

Thanks for reporting.

To let me reproduce your problem, please, indicate:
* your Linux distribution and version
* the program /bin/sh is invoking and its version
* the generated content of linux/deploy/version

**Comment by xypron** [comment]
@ballsystemlord 

Could you, please, check if the two patches I just committed solve your issue.

**Comment by ballsystemlord** [comment]
Thank xypron, for the quick fix!
